### ISSUE TITLE
Add support for svg images.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [cloudy-org/roseate#13]
Right now loading an svg fails because the `imagesize` crate doesn't support retrieving the width and height of an SVG (as stated here: https://github.com/Roughsketch/imagesize/issues/16).

This means we'll have to make use of another crate to grab the size like [svg-metadata](https://github.com/mre/svg-metadata) when we encounter an SVG file.

**Comment by r3tr0ananas** [comment]
If you want, i can try and do that.

**Comment by THEGOLDENPRO** [comment]
Yes you can give it a try in another branch, I'm just not entirely sure how well this will play with roseate. 

Like apparently there's svg files that will return a percentage for their width and height, how do we handle that? The [ImageSize](https://docs.rs/imagesize/0.13.0/imagesize/struct.ImageSize.html) struct in roseate takes width and height as **pixels**. Maybe [svg_metadata](https://docs.rs/svg_metadata/latest/svg_metadata/index.html) will actually have something to solve this and give us some sort of width and height.

This would probably be the code you will need to adjust: https://github.com/cloudy-org/roseate/blob/3a98fc490d659c8e7215389cab416bf0f70f986f/src/image.rs#L32-L44

The good part is that egui should be able to display svg files, at least I remember trying it with roseate in early development, so hopefully no changes need to be done there.

Let me know if you need help with anything.

**Comment by THEGOLDENPRO** [comment]
You probably want to have the code to handle svg files in a separate function though for modularity in case in the future we want to reuse it in another initialization function like `Image::from_url()`.

**Comment by THEGOLDENPRO** [comment]
Closing this now as #22 has been merged but like I said in my [comment](https://github.com/cloudy-org/roseate/pull/22#issuecomment-2455723121) this will need more work in the future.
