### ISSUE TITLE
Roeseate crashing on windows

### ISSUE THREAD

**Issue by Aertic** [cloudy-org/roseate#4]
The app crashes on windows before the img can be initialized

**Comment by THEGOLDENPRO** [comment]
Constantly getting this no matter what I do. 😢
```
[0414/204920.491:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
[0414/204920.527:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
thread 'main' panicked at src\main.rs:12:10:
error while running tauri application: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x8007139F, message: The group or resource is not in the correct state to perform the requested operation. }))))                                                                                                                                                                              ted operation. }))))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[0414/204921.062:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

**Comment by THEGOLDENPRO** [comment]
I found the culprit. It's cirrus theme handler:
https://github.com/cloudy-org/cirrus/blob/8410f609942994d0337f5b04c14dfe4c41d74a11/tauri_frontend/theme.ts#L15-L17

**Comment by THEGOLDENPRO** [comment]
It seems to only be breaking on Windows.

**Comment by THEGOLDENPRO** [comment]
For now, I'll disable this feature on Windows. This exact feature I'm trying to recreate here should hopefully land in Tauri v2: https://github.com/tauri-apps/tauri/issues/5279

So when we switch to v2 I can drop [the plugin](https://github.com/wyhaya/tauri-plugin-theme) I used for this.
