### ISSUE TITLE
rgba not supported with roseate's downsampler

### ISSUE THREAD

**Issue by r3tr0ananas** [cloudy-org/roseate#43]
I found that if you do 
```rust
let index = (
    relative_vertical_pos as usize * image_size.width + relative_horizontal_pos as usize
) * 4;
``` 
it fixes images like this:
![image](https://github.com/user-attachments/assets/326ba69f-447a-4f39-8395-9e8a46d71238)
but breaks other because of rgba and rgb images.

**Comment by r3tr0ananas** [comment]
So we need to check if the image is rgb or rgba.

**Comment by THEGOLDENPRO** [comment]
I knew the whole rgb and rgba thing and the way I was writing this downsampler would cause a bug like this.

**Comment by THEGOLDENPRO** [comment]
I've also been using these images for testing btw: https://github.com/Cykooz/fast_image_resize/tree/main/data

**Comment by r3tr0ananas** [comment]
#44 fixes this

**Comment by r3tr0ananas** [comment]
@THEGOLDENPRO so can i add myself to the authors in the cargo.toml?

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO so can i add myself to the authors in the cargo.toml? <img alt="" width="25" src="https://camo.githubusercontent.com/b28ae4da3f04212078e54e09ae627b216c48e866fec3910f9fe6198c15908e89/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f313237303832353334303934333539373631382e776562703f73697a653d3434">

go ahead
